services:
  crep-app-db:
    env_file:
      - path: .env
        required: true
    image: mysql
    container_name: crep-app-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - crep-app-network
  crep-app:
    container_name: crep-app
    image: node:20
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ${EXAM_FILES_UPLOAD_FOLDER}:${EXAM_FILES_UPLOAD_FOLDER}:rw
    stdin_open: true
    tty: true
    command: /bin/sh -c "cd /app && npm install && npm run dev"
    depends_on:
      crep-app-db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - EXAM_FILES_UPLOAD_FOLDER=${EXAM_FILES_UPLOAD_FOLDER}
    env_file:
      - .env
    networks:
      - crep-app-network
  crep-app-pma:
    image: phpmyadmin
    container_name: crep-app-pma
    restart: unless-stopped
    environment:
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      crep-app-db:
        condition: service_healthy
    ports:
      - 8088:80
    networks:
      - crep-app-network

networks:
  crep-app-network:
    name: crep-app-network